/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.edmacdonald.abcl.example.app;

import net.edmacdonald.abcl.example.list.LinkedList;

import static net.edmacdonald.abcl.example.utilities.StringUtils.join;
import static net.edmacdonald.abcl.example.utilities.StringUtils.split;
import static net.edmacdonald.abcl.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.util.encoders.Hex;

import java.security.Security;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

        Security.addProvider(new BouncyCastleProvider());

        Hex.decode();

    }
}
