/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.edmacdonald.abcl.example.app

internal object MessageUtils {
    @kotlin.jvm.JvmStatic
    val message: String
        get() = "Hello World! (from Ed)"
}