/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.edmacdonald.sumdigits;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @ParameterizedTest
    @MethodSource("sumTestData")
    void testSums(int expected, int actual) {
        assertEquals(expected, App.sumdigits(actual));
    }

    public static Stream<Arguments> sumTestData(){
        return Stream.of(
                Arguments.of(1, 1_000_000),
                Arguments.of(2, 100_100),
                Arguments.of(1+2+3+4+5+6, 123_456),
                Arguments.of(1+2, 100_002),
                Arguments.of(1+2, 1020),
                Arguments.of(5+2+1, 50120)
        );
    }
}
